config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  #resources :devise
  #resources :test

  root 'accounts#index'

  resources :accounts 

  # Scope Users, Agreements, Campaigns and Subscriptions for each Tenant
  scope ':tenant' do
    
    #Resources for User from Devise
    devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
    resources :devise

    #Resources for Campaign Subscription
    resources :campaigns do
      resources :subscriptions, only: [:new, :create]
    end

    #Resources for Agreements and Agreements Versions
    resources :agreements do
      collection do 
        get :deleted
      end
   
      resources :versions, only: [:destroy] do
        member do
          get :diff, to: 'versions#diff'
        end
      end
    end

    #Resources for Subscriptions
    #resources :subscriptions, only: [:index, :show]
    get 'subscriptions' => 'subscriptions#index', as: 'subscriptions'
    get 'subscriptions/:id' => 'subscriptions#show', as:'subscription'
    get 'subscriptions/:id/campaign' => 'subscriptions#campaign', as: 'campaign_subscription'
    get 'subscriptions/:id/agreement' => 'subscriptions#agreement', as: 'agreement_subscription'
    get 'subscriptions/:id/edit' => 'subscriptions#edit', as: 'edit_subscription'
    patch 'subscriptions/:id' => 'subscriptions#update'

  end

=begin
    resources :campaigns do
      resources :subscriptions, only: [:new, :create]
    end

    #resources :subscriptions, only: [:index, :show]
    get 'subscriptions' => 'subscriptions#index', as: 'subscriptions'
    get 'subscriptions/:id' => 'subscriptions#show', as:'subscription'
    get 'subscriptions/:id/campaign' => 'subscriptions#campaign', as: 'campaign_subscription'
    get 'subscriptions/:id/agreement' => 'subscriptions#agreement', as: 'agreement_subscription'
    get 'subscriptions/:id/edit' => 'subscriptions#edit', as: 'edit_subscription'
    patch 'subscriptions/:id' => 'subscriptions#update'
    
    #get 'campaigns/subscribe' => 'campaigns#subscribe'

    #mount Ckeditor::Engine => "/ckeditor"

    #get '/admin_users/login' => 'admin_users#login'
    #resources :admin_users

    root 'accounts#index'
    #root 'home#index'
    #root 'campaigns#index'

    resources :agreements do
      collection do 
        get :deleted
      end
   
      resources :versions, only: [:destroy] do
        member do
          get :diff, to: 'versions#diff'
        end
      end
    end
=end     

    #Resources for Versions to Bringback Agreements
    resources :versions, only: [] do
      member do
        patch :bringback
      end
    end

    get '/agreements/history', to: 'agreements#history', as: :agreement_history
    post '/agreements/:id/undo', to: 'agreements#undo', as: :undo

  #root 'campaign#show'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

  belongs_to :campaign
  belongs_to :agreement
  belongs_to :user

  def self.subcribed_campaign(user,campaign)
    campaign.subscriptions.find_by( user_id: user.id)
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  helper_method :campaigns_helper

  layout 'custom'
  before_action :current_user

  def agreement
    @subscription = Subscription.find(params[:id])
    @agreement = @subscription.agreement.version_at(@subscription.created_at)
    #byebug
  end
 
=begin 
  def campaign
    @subscription = Subscription.find(params[:id])
    @campaign = @subscription.campaign
  end
=end

  def index
    @subscriptions = current_user.subscriptions
  end
  
  def show
    @subscription = Subscription.find(params[:id])
    #@subscription = Campaign.find(params[:id])
  end

  def new
    @campaign = Campaign.friendly.find(params[:campaign_id])
    unless user_signed_in?
      session["user_return_to"] = new_campaign_subscription_path(@campaign, tenant: @campaign.account.url)
      redirect_to new_user_session_path and return
    end 

    @subscription = Subscription.new
    @subscription.campaign = @campaign
  end

  def edit
    @subscription = Subscription.find(params[:id])
  end

  def update
    @subscription = Subscription.find(params[:id])
    if @subscription.update(subscription_params)
      redirect_to subscription_path(@subscription)
    else
      render :edit
    end
  end

  def create
    @campaign = Campaign.friendly.find(params[:campaign_id])
    unless user_signed_in?
      session["user_return_to"] = new_campaign_subscription_path(@campaign, tenant: @campaign.account.url)
      redirect_to new_user_session_path and return
    end 

    #redirect_to campaigns_path
    @subscription = Subscription.new(subscription_params)
    @subscription.user_id = current_user.id
    @subscription.agreement_id = @campaign.agreement_id
    
    if @subscription.valid? && @subscription.save
      redirect_to subscription_path(@subscription, tenant: @campaign.account.url), notice: t(:subscription_ok)
    else
      render :new
    end
  end

  private

    def subscription_params
      params.require(:subscription).permit(:email, :address1, :address2, :zip_code, :zip_location, :phone_number, :cell_phone_number, :agreement_id, :campaign_id, :user_id)
    end

end

app/views/subscriptions/edit.html.erb
<div class="campaigns-header">
  <h1><%= t(:edit) %></h1>
</div>

<section class="bg-primary" id="about">
  <div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">   
      <%= form_for(@subscription) do |f| %>
        <div class="panel panel-default">
          <div class="panel-body">
         
            <p>
              <%= t(:email) %><br />
              <%= f.email_field :email, autofocus: true, class: "textfield" %>
            </p>
            
            <p>
              <%= t(:address1) %>:
              <%= f.text_field :address1 %><br>

              <%= t(:address2) %>:
              <%= f.text_field :address2 %>
            </p>
        
            <p>
              <%= t(:zip_code) %>:
              <%= f.text_field :zip_code %>
            </p>

            <p>
              <%= t(:zip_location) %>:
              <%= f.text_field :zip_location %>
            </p>

            <p>
              <%= t(:phone_number) %>:
              <%= f.text_field :phone_number %>
            </p>

            <p>
              <%= t(:cell_phone_number) %>:
              <%= f.text_field :cell_phone_number %>
            </p>

            <p>
              <%= f.submit t(:update), class: "btn btn-primary" %>
              <%= link_to t(:back), :back , class: "btn btn-primary" %>
            <p>


          </div>
        </div>    
      <% end %> 
    </div>
  </div>
</section>

app/views/subscriptions/index.html.erb
<div class="campaigns-header">
  <h1><%= t(:my_campaigns) %></h1>
</div>

<section class="bg-primary" id="about">
  <div class="container">
    <div class="row">
      <% @subscriptions.each do |subscription| %>
        <%= render partial: 'shared/campaign', locals: {campaign: subscription.campaign} %>
        
        <% if false %>
        <div class="col-md-4 col-sm-6">
          <div class="panel panel-default">
            <div class="panel-heading">
            <%= subscription.campaign.name %>
            </div>
            <div class="panel-body">
              <p>
                <%= subscription.agreement.name %>
              </p>

            </div>
            <div class="panel-footer">
              <p>
                <b><%= link_to t(:show), subscription_path(subscription), class: "btn btn-primary" %></b>
              </p>
            </div>
          </div>
        </div>
        <% end %>

      <% end %>
    </div>
  </div>
</section>

app/views/subscriptions/new.html.erb
<div class="campaigns-header">
  <h1>Campaign Subscription</h1>
</div>

<section class="bg-primary" id="about">
  <div class="container">
    <div class="row">

        <div class="col-md-6 col-sm-6">
          <div class="panel panel-default">
            <div class="panel-heading">
            <%= @campaign.name %>
            </div>
            <div class="panel-body">
              <p>
                <%= @campaign.introduction %>
              </p>
              <p>
                <%= image_tag @campaign.image.url(:large).to_s if @campaign.image? %>              
                <br>                
                <b><%= t(:start_date) %>:</b>
                <%= @campaign.start_date %>
                <br>
                <b><%= t(:end_date) %>:</b>
                <%= @campaign.end_date %>
              </p>
            </div>
            <div class="panel-footer">
              <p>
                <b><%= link_to t(:show), campaign_path(@campaign, tenant: @campaign.account.url), class: "btn btn-primary" %></b>
              </p>
            </div>
          </div>
        </div>

        <div class="col-md-6 col-sm-6">
          <% url = url_for(controller: 'subscriptions', action: 'create') %>
          <%= form_for(@subscription, url: url) do |f| %>
            <div class="panel panel-default">
              <div class="panel-body">
                <p>
                  <%= t(:email) %>
                  <%= f.text_field :email, autofocus: true, class: "textfield" %><br />
                </p>
                <p>
                  <%= t(:address1) %>
                  <%= f.text_field :address1, autofocus: true, class: "textfield" %><br />
                </p>
                <p>
                  <%= t(:address2) %>
                  <%= f.text_field :address2, autofocus: true, class: "textfield" %><br />
                </p>
                <p>
                  <%= t(:zip_code) %>
                  <%= f.text_field :zip_code, autofocus: true, class: "textfield" %><br />
                </p>
                <p>
                  <%= t(:zip_location) %>
                  <%= f.text_field :zip_location, autofocus: true, class: "textfield" %><br />
                </p>
                <p>
                  <%= t(:phone_number) %>
                  <%= f.text_field :phone_number, autofocus: true, class: "textfield" %><br />
                </p>
                <p>
                  <%= t(:cell_phone_number) %>
                  <%= f.text_field :cell_phone_number, autofocus: true, class: "textfield" %><br />
                </p>
                <p>
                  <%= f.hidden_field :campaign_id %>
                </p>              
              </div>
              <div class="panel-footer">
                <p>
                  <%= f.submit t(:subscribe), class: "btn btn-primary" %>
                  <%= link_to t(:back), campaigns_path(tenant: @campaign.account.url), class: "btn btn-primary" %>
                </p>
              </div>
            </div>
          <% end %>
        </div>

    </div>
  </div>
</section>

app/views/subscriptions/show.html.erb
<div class="campaigns-header">
  <h1><%= t(:subscription) %></h1>
</div>

<section class="bg-primary" id="about">
  <div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <div class="panel panel-default">
          <div class="panel-body">

            <p id="notice"><%= notice %></p>
            
            <p>
              <%= t(:email) %>:
              <%= @subscription.email %>
            </p>
            
            <p>
              <%= t(:address1) %>:
              <%= @subscription.address1 %><br>
              <%= t(:address2) %>:
              <%= @subscription.address2 %>
            </p>
        
            <p>
              <%= t(:zip_code) %>:
              <%= @subscription.zip_code %>
            </p>

            <p>
              <%= t(:zip_location) %>:
              <%= @subscription.zip_location %>
            </p>

            <p>
              <%= t(:phone_number) %>:
              <%= @subscription.phone_number %>
            </p>

            <p>
              <%= t(:cell_phone_number) %>:
              <%= @subscription.cell_phone_number %>
            </p>

            <p>
              <%= t(:campaign) %>:
              <%= @subscription.campaign.name %>
            </p>

            <p>
              <%= t(:agreement) %>:
              <%= @subscription.agreement.name %>
            </p>

            <p>
              <%= link_to t(:back), subscriptions_path, class: "btn btn-primary" %>
            <p>
              <% if false %>
              <%= link_to t(:edit), edit_subscription_path, class: "btn btn-primary" %>
              <% end %>

          </div>
        </div>     
    </div>
  </div>
</section>