config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  #resources :devise
  #resources :test

  root 'accounts#index'

  resources :accounts 

  # Scope Users, Agreements, Campaigns and Subscriptions for each Tenant
  scope ':tenant' do
    
    #Resources for User from Devise
    devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
    resources :devise

    #Resources for Campaign Subscription
    resources :campaigns do
      resources :subscriptions, only: [:new, :create]
    end

    #Resources for Agreements and Agreements Versions
    resources :agreements do
      collection do 
        get :deleted
      end
   
      resources :versions, only: [:destroy] do
        member do
          get :diff, to: 'versions#diff'
        end
      end
    end

    #Resources for Subscriptions
    #resources :subscriptions, only: [:index, :show]
    get 'subscriptions' => 'subscriptions#index', as: 'subscriptions'
    get 'subscriptions/:id' => 'subscriptions#show', as:'subscription'
    get 'subscriptions/:id/campaign' => 'subscriptions#campaign', as: 'campaign_subscription'
    get 'subscriptions/:id/agreement' => 'subscriptions#agreement', as: 'agreement_subscription'
    get 'subscriptions/:id/edit' => 'subscriptions#edit', as: 'edit_subscription'
    patch 'subscriptions/:id' => 'subscriptions#update'

  end

=begin
    resources :campaigns do
      resources :subscriptions, only: [:new, :create]
    end

    #resources :subscriptions, only: [:index, :show]
    get 'subscriptions' => 'subscriptions#index', as: 'subscriptions'
    get 'subscriptions/:id' => 'subscriptions#show', as:'subscription'
    get 'subscriptions/:id/campaign' => 'subscriptions#campaign', as: 'campaign_subscription'
    get 'subscriptions/:id/agreement' => 'subscriptions#agreement', as: 'agreement_subscription'
    get 'subscriptions/:id/edit' => 'subscriptions#edit', as: 'edit_subscription'
    patch 'subscriptions/:id' => 'subscriptions#update'
    
    #get 'campaigns/subscribe' => 'campaigns#subscribe'

    #mount Ckeditor::Engine => "/ckeditor"

    #get '/admin_users/login' => 'admin_users#login'
    #resources :admin_users

    root 'accounts#index'
    #root 'home#index'
    #root 'campaigns#index'

    resources :agreements do
      collection do 
        get :deleted
      end
   
      resources :versions, only: [:destroy] do
        member do
          get :diff, to: 'versions#diff'
        end
      end
    end
=end     

    #Resources for Versions to Bringback Agreements
    resources :versions, only: [] do
      member do
        patch :bringback
      end
    end

    get '/agreements/history', to: 'agreements#history', as: :agreement_history
    post '/agreements/:id/undo', to: 'agreements#undo', as: :undo

  #root 'campaign#show'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/agreement.rb
class Agreement < ActiveRecord::Base

#  default_scope { where(customer_id: Customer.current_id) if Customer.current_id }


  acts_as_tenant(:account)
  validates_uniqueness_to_tenant :name

  
  belongs_to :admin_user
  belongs_to :account

  has_many :campaigns

  accepts_nested_attributes_for :campaigns, :allow_destroy => true

  def admin_user_name
    admin_user ? admin_user.id : ''
  end

  has_paper_trail
  has_paper_trail class_name: 'AgreementVersion'#, meta: { author_username: :user_name, word_count: :count_word}
  
  #has_paper_trail ignore: [:view_count]

  #has_paper_trail meta: { timestamp: Time.now }

end

app/controllers/agreements_controller.rb
class AgreementsController < ApplicationController
  before_action :current_user
  before_action :set_document, only: [:show, :edit, :update, :destroy]


  # GET /documents
  # GET /documents.json
  def index
    @agreements = Agreement.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @agreement = Agreement.find(params[:id])
  end

  def deleted
    @agreements = AgreementVersion.where(event: 'destroy')
  end

  # GET /documents/new
  def new
    @agreements = Agreement.new
  end

  # GET /documents/1/edit
  def edit
    @agreement = Agreement.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @agreements = Agreement.new(agreement_params)
    @agreements.admin_user_id = current_admin_user.id

    if @agreements.save
      redirect_to agreements_path(@agreement), notice: "New agreements saved."
    else
      render :new
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    @agreements = Agreement.find(params[:id])
    if @agreements.update(agreement_params)
      #flash[:success] = "Agreement was updated! #{make_undo_link}"
      redirect_to agreements_path(@agreements)
    else
      render :edit
    end
  end
  

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @agreements = Agreement.find(params[:id])
    @agreements.destroy
    redirect_to agreements_path(@agreements), notice: 'Agreement was successfully destroyed.'
    
  end


  def history
    @versions = PaperTrail::Version.order('created_at DESC')
  end

  private

  #def undo
  #  @agreements_version = PaperTrail::Version.find_by_id(params[:id])

  #  begin
  #    if @agreements_version.reify
  #      @agreements_version.reify.save
  #    else
  #      # For undoing the create action
  #      @agreements_version.item.destroy
  #    end
  #    flash[:success] = "Undid that! #{make_redo_link}"
  #  rescue
  #    flash[:alert] = "Failed undoing the action..."
  #  ensure
  #    redirect_to root_path
  #  end
  #end

  #def make_undo_link
  #  view_context.link_to 'Undo that plz!', undo_path(@agreements.versions.last), method: :post
  #end

  #def make_redo_link
  #  params[:redo] == "true" ? link = "Undo that plz!" : link = "Redo that plz!"
  #  view_context.link_to link, undo_path(@agreement_version.next, redo: !params[:redo]), method: :post
  #end


  #Use callbacks to share common setup or constraints between actions.
  def set_document
    @agreements = Agreement.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def agreement_params
    params.require(:agreement).permit(:name, :text, :publish_at, :discontinued_at, :user_id)
  end
end

app/helpers/agreement_helper.rb
module AgreementHelper
  
  def find_version_author_name(version)
    admin_user = AdminUser.find_version_author(version) 
    admin_user ? admin_user.id : ''
  end

  def diff(text1, text2)
   changes = Diffy::Diff.new(text1, text2, include_plus_and_minus_in_html: true, include_diff_info: true)
   changes.to_s.present? ? changes.to_s(:html).html_safe : 'No Changes'
  end

end

app/views/agreements/_form.html.erb
<%= form_for(@agreements) do |f| %>
  <% if @agreements.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agreements.errors.count, "error") %> prohibited this agreements from being saved:</h2>

      <ul>
      <% @agreements.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :text %><br>
    <%= f.cktext_area :text %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :admin_user_id %>
  </div>

  <% if false %>
  <div class="form-group">
    <%= f.label :publish_at %><br>
    <%= f.datetime_select :publish_at, { :start_year => 1990 } %>
  </div>
  <div class="form-group">
    <%= f.label :discontinued_at %><br>
    <%= f.datetime_select :discontinued_at %>
  </div>
  <% end %>
  <br>
  <br>
  <div class='fr'>
    <%= f.submit 'Save' %>
    <%= link_to 'Back', :back %>
  </div>
<% end %>

app/views/agreements/_versions.html.erb
<h2>Previous Versions</h2>
 
<table class='table'>
  <thead>
    <tr>
      <th>Index</th>
      <th>Date</th>
      <% if false %><th>Author</th><% end %>
      <th>Event</th>
      <th></th>
    </tr>
  </thead>
 
  <tbody>
    <%- agreement.versions.reverse.each do |version| %>
      <tr>
        <td><%= raw version.index %></td>
        <td><%= version.created_at %></td>
        <% if false %><td><%= find_version_author_name(version) %></td><% end %>
        <td><%= version.event.humanize %></td>
        <td><%= link_to 'Diff', diff_agreement_version_path(agreement, version) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/agreements/deleted.html.erb
<h1>Bring back agreement</h1>
<table class='table'>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th>Deleted by</th>
      <th>At</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @agreements.each do |agreement_version| %>
      <%- agreement = agreement_version.reify %>
      <tr>
        <td><%= agreement.id %></td>
        <td><%= agreement.name %></td>
        <td><%= agreement.content %></td>
        <td><%= find_version_author_name(agreement_version) %></td>
        <td><%= agreement.created_at %></td>
        <td><%= link_to 'Bringback', bringback_version_path(agreement_version), method: 'PATCH' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Back', agreements_path %>

app/views/agreements/edit.html.erb
<h1>Editing agreements</h1>

<%= render 'form' %>
<br>
<br>
<%= render 'agreements/versions', agreement: @agreement %>

app/views/agreements/history.html.erb
<div class="container">
  <h1>History</h1>

  <ul>
    <% @versions.each do |version| %>
      <li>
        <%= l(version.created_at, format: "%-d.%m.%Y %H:%M:%S %Z") %><br/>
        Event ID: <%= version.id %><br/>
        <b>Target:</b> <%= version.item_type %>
        <small>(id: <%= version.item_id %>)</small>; <b>action</b> <%= version.event %>;<br/>
        <div>
          More info:
          <pre><%= version.object %></pre>
        </div>
      </li>
    <% end %>
  </ul>
</div>
<div>
  Changeset:
  <pre><%= version.changeset %></pre>
</div>
<b>Remote address:</b> <%= version.ip %><br/>

<b>User:</b>
<% if version.whodunnit && version.whodunnit != 'Guest' %>
  <% user = User.find_by_id(version.whodunnit) %>
  <% if user %>
    <%= user.email %>
    (last seen at <%= l(user.last_sign_in_at, format: "%-d.%m.%Y %H:%M:%S") %>)
  <% end %>
<% else %>
  Guest
<% end %>

app/views/agreements/index.html.erb
<h1>Listing agreements</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agreements.each do |agreement| %>
      <tr>
        <td><%= raw agreement.name %></td>
        <td><%= raw agreement.admin_user_id %></td>
        <td><%= link_to 'Show', agreement_path(agreement, account: agreement.account.url) %></td>
        <td><%= link_to 'Edit', edit_agreement_path(agreement, account: agreement.account.url) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New agreement', new_agreement_path %>

app/views/agreements/new.html.erb
<h1>New agreement</h1>

<%= render 'form' %>

app/views/agreements/show.html.erb
<div class="campaigns-header">
  <h1><%= raw @agreement.name %></h1>
</div>

<section class="bg-primary" id="about">
  <div class="container">
    <div class="row">

        <div class="col-md-8 col-md-offset-2 col-sm-6 col-sm-offset-3">
          <div class="panel panel-default">
            <div class="panel-body">
              <p>
                <%= raw @agreement.text %>
              </p>
              
            </div>
            <div class="panel-footer">
              <p>
                <b><%= link_to t(:back), campaigns_path, class: "btn btn-primary" %></b>
              </p>
            </div>
          </div>
        </div>

    </div>
  </div>
</section>