config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  #resources :devise
  #resources :test

  root 'accounts#index'

  resources :accounts 

  # Scope Users, Agreements, Campaigns and Subscriptions for each Tenant
  scope ':tenant' do
    
    #Resources for User from Devise
    devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
    resources :devise

    #Resources for Campaign Subscription
    resources :campaigns do
      resources :subscriptions, only: [:new, :create]
    end

    #Resources for Agreements and Agreements Versions
    resources :agreements do
      collection do 
        get :deleted
      end
   
      resources :versions, only: [:destroy] do
        member do
          get :diff, to: 'versions#diff'
        end
      end
    end

    #Resources for Subscriptions
    #resources :subscriptions, only: [:index, :show]
    get 'subscriptions' => 'subscriptions#index', as: 'subscriptions'
    get 'subscriptions/:id' => 'subscriptions#show', as:'subscription'
    get 'subscriptions/:id/campaign' => 'subscriptions#campaign', as: 'campaign_subscription'
    get 'subscriptions/:id/agreement' => 'subscriptions#agreement', as: 'agreement_subscription'
    get 'subscriptions/:id/edit' => 'subscriptions#edit', as: 'edit_subscription'
    patch 'subscriptions/:id' => 'subscriptions#update'

  end

=begin
    resources :campaigns do
      resources :subscriptions, only: [:new, :create]
    end

    #resources :subscriptions, only: [:index, :show]
    get 'subscriptions' => 'subscriptions#index', as: 'subscriptions'
    get 'subscriptions/:id' => 'subscriptions#show', as:'subscription'
    get 'subscriptions/:id/campaign' => 'subscriptions#campaign', as: 'campaign_subscription'
    get 'subscriptions/:id/agreement' => 'subscriptions#agreement', as: 'agreement_subscription'
    get 'subscriptions/:id/edit' => 'subscriptions#edit', as: 'edit_subscription'
    patch 'subscriptions/:id' => 'subscriptions#update'
    
    #get 'campaigns/subscribe' => 'campaigns#subscribe'

    #mount Ckeditor::Engine => "/ckeditor"

    #get '/admin_users/login' => 'admin_users#login'
    #resources :admin_users

    root 'accounts#index'
    #root 'home#index'
    #root 'campaigns#index'

    resources :agreements do
      collection do 
        get :deleted
      end
   
      resources :versions, only: [:destroy] do
        member do
          get :diff, to: 'versions#diff'
        end
      end
    end
=end     

    #Resources for Versions to Bringback Agreements
    resources :versions, only: [] do
      member do
        patch :bringback
      end
    end

    get '/agreements/history', to: 'agreements#history', as: :agreement_history
    post '/agreements/:id/undo', to: 'agreements#undo', as: :undo

  #root 'campaign#show'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/account.rb
class Account < ActiveRecord::Base
  
  #extend FriendlyId
  #friendly_id :name, use: :slugged
  
  has_many :agreements
  has_many :campaigns
  has_many :users

  accepts_nested_attributes_for :agreements, :allow_destroy => true
  accepts_nested_attributes_for :campaigns, :allow_destroy => true
  accepts_nested_attributes_for :users, :allow_destroy => true

  def self.current_id=(id)
    Thread.current[:account_id] = id
  end

  def self.account_id
    Thread.current[:account_id]
  end
  
  mount_uploader :image, ImageUploader

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  def index
    @accounts = Account.all
  end

  def show
    #redirect_to 
    @campaign = Account.find(params[:url])
  end
  
end

app/views/accounts/_index.html.erb
<div class="campaigns-header">
  <h1><%= t(:accounts) %></h1>
</div>

<section class="bg-primary" id="about">
  <div class="container">
    <div class="row">
      <% @accounts.each do |account| %>
        <div class="col-md-4 col-sm-6">
          <div class="panel panel-default">
            <div class="panel-heading">
            <%= account.name %>
            </div>
            <div class="panel-body">
              <p>
                <%= image_tag account.image.url(:large).to_s if account.image? %>              
              </p>
            </div>
            <div class="panel-footer">

            <% if true  %>
              <p>
                <b><%= link_to t(:show), campaign_path(campaign, tenant: campaign.account.url), class: "btn btn-primary" %></b>
                <b><%= link_to t(:subscribe), new_campaign_subscription_path(campaign, tenant: campaign.account.url), class: "btn btn-primary" %></b>
              </p>
            <% end %>
            
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/accounts/index.html.erb
<div class="campaigns-header">
  <h1><%= t(:accounts) %></h1>
</div>

<section class="bg-primary" id="about">
  <div class="container">
    <div class="row">
      <% @accounts.each do |account| %>
        <%= render partial: 'shared/account', locals: {account: account} %>
      <% end %>
    </div>
  </div>
</section>

app/views/accounts/show.html.erb
<div class="campaigns-header">
  <h1><%= @campaign.name %></h1>
</div>

<section class="bg-primary" id="about">
  <div class="container">
    <div class="row">

        <div class="col-md-8 col-md-offset-2 col-sm-6 col-sm-offset-3">
          <div class="panel panel-default">
            <div class="panel-body">
              <p>
                <%= @campaign.introduction %>
              </p>
              <p>
                <%= @campaign.description %>
              </p>
              <p>
                <%= @campaign.product %>
              </p>
              <p>
                <%= image_tag @campaign.image.url(:thumb).to_s if @campaign.image? %>
              </p>
              <p>
                <%= link_to @campaign.agreement.name, agreement_path(@campaign, account: campaign.account.url) %>
              </p>
              <p>
                <b><%= t(:start_date) %>:</b>
                <%= @campaign.start_date %>
              </p>
              <p>                
                <b><%= t(:end_date) %>:</b>
                <%= @campaign.end_date %>
              </p>
            </div>
            <div class="panel-footer">
              <p>
                <b><%= link_to t(:back), campaigns_path, class: "btn btn-primary" %></b>
                <b><%= show_subscribe_or_message(@campaign, account: campaign.account.url) %></b>
              </p>
            </div>
          </div>
        </div>

    </div>
  </div>
</section>